### ISSUE TITLE
Usecase request - Time converter

### ISSUE THREAD

**Issue by sabyasachi2505** [frifty-search/search-apps#2]
**Problem**
A user is currently juggling work between 3 timezones. It is difficult to convert a given date and time to two other timezones.

**Describe the solution you'd like**
Need a frifty box that is divided into 3 vertical segments. The left most one is based on user input (Selects a timezone and then sets the date and time). The other 2 segments on the right should allow the user to decide the timezones. On pressing a "Convert" button the magic happens.

**Desired functionality**
Capture the timezones that the user sets in each of the boxes and set that to default going forward.

**Comment by Aman-201** [comment]
hello @StrangeNoob 
I am intrested to solve this issue and contribute to solve this.

**Comment by StrangeNoob** [comment]
Sure @Aman-201 ,
You can take up this issues

**Comment by StrangeNoob** [comment]
Close with #4
