### ISSUE TITLE
Usecase request - Air Pollution

### ISSUE THREAD

**Issue by StrangeNoob** [frifty-search/search-apps#3]
**Problem**
A user wants to know the air quality of any city.

**Describe the solution you'd like**
Need a frifty box that is divided into 2 horizontal segments. The first one will be a text field that will take a city name as input.  The second will be a button named "Checked". On pressing a "Check" button the magic happens.

**Desired functionality**
Capture the city name that the user sets and show the proper result.

**Comment by Aman-201** [comment]
hello @StrangeNoob 
I am intrested to solve this issue and contribute to solve this.
please give me chance to contibute.

**Comment by StrangeNoob** [comment]
Sure @Aman-201, 
You can take up this issues

**Comment by StrangeNoob** [comment]
Close this Issue with the pr #9 .
