### ISSUE TITLE
Usecase request - Compound Interest Calculator

### ISSUE THREAD

**Issue by StrangeNoob** [frifty-search/search-apps#5]
**Is your usecase request related to a problem? Please describe.**
In order to calculate a compound, users don't have to visit multiple websites. Create a Widget interactive enough to perform those operations

**Describe the solution you'd like**

Have 3 text fields column-wise to get user inputs and calculate below that to required operations.

**Comment by Aman-201** [comment]
hello sir,
i am interested to solve this issue.

**Comment by StrangeNoob** [comment]
Hello @Aman-201,

You can take up this issue. And Can work on it.
