### ISSUE TITLE
Usecase request - CGPA to Percentage Calculator

### ISSUE THREAD

**Issue by StrangeNoob** [frifty-search/search-apps#6]
**Is your usecase request related to a problem? Please describe.**
In order to convert cgpa to percentage, users don't have to visit multiple websites. Create a Widget interactive enough to perform those operations
**Describe the solution you'd like**
Have a Textield to take user input and  below that a calculate button to do needful operations

**Comment by Aman-201** [comment]
hello sir,
I am keen to solve the issue given above.

**Comment by StrangeNoob** [comment]
Hello @Aman-201 ,

You can take up this issue. And Can work on it.
